In [4]:
import numpy as np

## THE BASICS

In [5]:
a = np.array([1,2,3,4,5],dtype='int16')
print(a)

[1 2 3 4 5]


In [6]:
b = np.array([[1,2,3,4,5] ,[6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
# GET DIMENSION
a.ndim

1

In [8]:
# GET SHAPE
a.shape

(5,)

In [9]:
# data type
print(a.dtype)
print(b.dtype)

int16
int64


In [10]:
#data size
print(a.itemsize)
b.itemsize

2


8

In [11]:
# total size of the vector
print(a.nbytes)
b.nbytes

10


80