In [41]:
import numpy as np


In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
b= np.array([[1,2,3],[4,5,6],[7,8,9]])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### TO GET A SPECIFIC ELEMENT
----

In [43]:
a[1,1]

np.int64(9)

In [44]:
#GET a SPECIFIC ROW
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
# GET A SPECIFIC COLUMN
a[:,6]

array([ 7, 14])

In [46]:
# step size array[row_index, column_start:column_end:step]
print(a[0,1:6:2])
print(a[1,1:6])

[2 4 6]
[ 9 10 11 12 13]


### REPLACING A NUMBER INSIDE THE MATRICE
---

In [47]:
a[1,5]= 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [50]:
b[1:,2] = 0
print(b)

[[1 2 3]
 [4 5 0]
 [7 8 0]]


* 3d example


In [54]:
c = np.array([[[1,23],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
# work your way outside out
print(c[0:1,:,0:1])

[[[1]
  [3]]]


## DETAIL BREAK DOWN OD SLICING IN 3D ARRAY

In [77]:
x = np.arange(2,56,2)
x.resize(3,3,3)
print(x)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]


In [78]:
x[0:2] # layer along z

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [79]:
x[0:2,0:2] # rows

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[20, 22, 24],
        [26, 28, 30]]])

In [80]:
x[0:2,0:2,0:2]

array([[[ 2,  4],
        [ 8, 10]],

       [[20, 22],
        [26, 28]]])