In [3]:
import numpy as np

### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
c= np.matmul(a,b)
print(c)

In [10]:
c = np.identity(3)
det_c = np.linalg.det(c)
print(det_c)
inv_c = np.linalg.inv(c)
print(inv_c)

1.0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### STATISTICS


In [23]:
stats = np.random.randint(0,9,size=(3,3))
print(stats)
np.max(stats)

[[0 6 7]
 [3 5 7]
 [8 2 4]]


np.int32(8)

In [25]:
np.min(stats,axis=0)

array([0, 2, 4], dtype=int32)