In [2]:
import numpy as np


#### REORGANIZING ARRAYS

In [ ]:
%%sql


In [13]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### vertically stacking vectors

In [5]:
v1 = np.array([[1,2,33,43],[5,6,7,8]])
v2 = np.array([[13,22,31,40],[50,61,2,32]])
print(np.vstack([v1,v2,v2]))

[[ 1  2 33 43]
 [ 5  6  7  8]
 [13 22 31 40]
 [50 61  2 32]
 [13 22 31 40]
 [50 61  2 32]]


### horizontal staking

In [7]:
h1 = np.array([[1,2],[2,3]])
h2 = np.array([[5,6],[7,8]])
print(np.hstack([h1,h2]))

[[1 2 5 6]
 [2 3 7 8]]


In [8]:
h3= np.ones(3)