In [1]:
import numpy as np


## Miscellaneous
----
#### Load data from a file

In [11]:
file_data = np.genfromtxt('dataset.txt', delimiter=',')
print(file_data)

[[  nan   nan   nan   nan]
 [172.5  68.2  25.   82.1]
 [160.1  55.4  30.   70. ]
 [185.3  90.5  45.   92.7]
 [177.   75.2  34.   88.5]
 [165.6  60.   28.   67.4]
 [158.9  52.1  22.   74. ]
 [190.2  85.3  40.   95.6]
 [153.   50.   19.   61.2]
 [169.7  72.8  33.   78.9]
 [174.8  65.4  26.   85.3]
 [180.   78.   29.   91. ]
 [162.3  58.6  27.   69.5]
 [166.4  63.3  38.   74.9]
 [157.8  54.1  24.   66. ]
 [176.9  70.5  36.   82.7]
 [188.   92.2  43.   89.4]
 [159.3  53.   21.   60. ]
 [170.5  66.7  32.   80.2]
 [175.6  73.9  31.   77.3]
 [183.7  88.6  41.   90.1]]


#### Boolean Masking and Adavanced indexing

In [ ]:
file_data > 50

In [15]:
np.any(file_data > 50 ,axis=1)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [19]:
((file_data > 50) & (file_data < 100))

array([[False, False, False, False],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False, False, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])