In [1]:
import numpy as np


In [4]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.array([11,12,13,14,15])
d=np.array([16,17,18,19,20])
e=np.array([21,22,23,24,25])
f=np.array([26,27,28,29,30])
mat = np.vstack([a,b,c,d,e,f])
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
mat[2:4,0:2]

In [21]:
for i in range(0,5):
    print(mat[i:i+1,i+1:i+2],end='\n\t')


[[2]]
	[[8]]
	[[14]]
	[[20]]
	[]
	

In [23]:
for i in range(0,5):
    print(mat[i:i+1,i+3:i+5])

[[4 5]]
[[10]]
[]
[]
[]


## 100 practice question