## INITALIZING DIFFERENT TYPES OF ARRAYS

In [2]:
import numpy as np


#### 2 → The number of blocks (first dimension)
#### 3 → Each block contains 3 groups (second dimension)
#### 3 → Each group contains 3 rows (third dimension)
#### 2 → Each row contains 2 columns (fourth dimension)


In [ ]:
# All 0s matrices
np.zeros((2,3,3,2))

In [16]:
np.full((2,3,3,2),99)

array([[[[99, 99],
         [99, 99],
         [99, 99]],

        [[99, 99],
         [99, 99],
         [99, 99]],

        [[99, 99],
         [99, 99],
         [99, 99]]],


       [[[99, 99],
         [99, 99],
         [99, 99]],

        [[99, 99],
         [99, 99],
         [99, 99]],

        [[99, 99],
         [99, 99],
         [99, 99]]]])

In [20]:
# random decimal numbers
np.random.rand(2,3,3,2)

array([[[[0.74282643, 0.40899616],
         [0.23189595, 0.68483686],
         [0.67748104, 0.8809182 ]],

        [[0.46368338, 0.13959434],
         [0.80434838, 0.99677534],
         [0.79935525, 0.21982414]],

        [[0.58283447, 0.71422894],
         [0.48638463, 0.35600538],
         [0.56187774, 0.37289642]]],


       [[[0.24065417, 0.57289916],
         [0.13087374, 0.28595652],
         [0.75544311, 0.70836436]],

        [[0.4791383 , 0.31472151],
         [0.14013287, 0.89291925],
         [0.13754432, 0.26615381]],

        [[0.70168336, 0.90947951],
         [0.60458008, 0.5214481 ],
         [0.50692451, 0.91422179]]]])

In [38]:
print(np.random.randint(7,size=(3,3)))

[[1 3 2]
 [4 3 2]
 [2 5 6]]


In [41]:
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
#  repeat an array
arr = np.array([[1,2,3]])
r1 =np.repeat(arr,2,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]]


#### PRACTICE QUESTION
     1 1 1 1 1
     1 0 0 0 1
     1 0 9 0 1
     1 0 0 0 1
     1 1 1 1 1
---
- output = np.ones((5,5),dtype='int32')
- print(output)
- z = np.zeros((3,3))
- z[1,1]=9
- output[1:4 ,1:4] = z
- print(output)

In [54]:
output = np.ones((5,5),dtype='int32')
output[1:4,1:4] = 0
output[2,2] = 9
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### BE CAREFUL COPYING AN ARRAY

In [56]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]


In [57]:
# correct way
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


#### MATHEMATICS


In [68]:
mat = np.array([1,2,3,4])
print(mat)

[1 2 3 4]


In [69]:
mat = mat+2
print(mat)

[3 4 5 6]


In [71]:
mat = mat-2
print(mat)

[-1  0  1  2]


In [73]:
mat = mat *2
print(mat)

[-4  0  4  8]


In [75]:
mat= mat/2
print(mat)

[-1.  0.  1.  2.]


In [78]:
mat = mat**2
print(mat)

[ 4.  0.  4. 16.]
